# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a16452495346d7366274d41e3fa5c8a0a6db4e04a50f0b22e31ee9aac176c905174c2d14ae0531ac6d5555afdc85877f7a5638aca40c16348301ea1bbdc2afd

test:
  secret_key_base: 84f0249de114e12edb33b75a56684995ee96d65021b5ec9614c9da7892fabba8634890a9314ae27f3b22b95f68274288f61309a98df8732f7fdd17ef5fc30ad6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
